Finished build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -6,5 +6,83 @@ jobs:
   build:
     runs-on: ubuntu-latest
     steps:
-      - name: LightDream Gradle Build
-        uses: L1ghtDream/gradle-build@1.0.0
+      - name: Setup codebase
+        uses: actions/checkout@v2
+
+      - name: Setup Java
+        uses: actions/setup-java@v2
+        with:
+          distribution: temurin
+          java-version: 17
+
+      - name: Setup Gradle
+        uses: gradle/gradle-build-action@v2
+
+      - name: Execute Gradle build
+        run: gradle build
+
+      - name: Set version env variable
+        run: |
+          echo "VERSION=$(gradle properties -q | grep "version:" | awk '{print $2}')" >> $GITHUB_ENV
+          echo "ARTIFACT=$(gradle properties -q | grep "name:" | awk '{print $2}')" >> $GITHUB_ENV
+          echo "GROUP=$(gradle properties -q | grep "group:" | awk '{print $2}')" >> $GITHUB_ENV
+          echo "REPOSITORY_NAME=$(echo ${{ github.repository }} | awk -F'/' '{print $2}')" >> $GITHUB_ENV
+      - name: Uploading artifacts
+        run: |
+          touch ~/.gradle/gradle.properties
+          echo "
+            gitlab.url = https://gitlab.com/api/v4/projects/41661215/packages/maven/
+            gitlab.auth.header.name = Private-Token
+            gitlab.auth.header.value = ${{ secrets.GITLAB_AUTH_HEADER_VALUE }}
+          
+            github.url = https://maven.pkg.github.com/${{ github.REPOSITORY }}
+            github.auth.username = L1ghtDream
+            github.auth.password = ${{ secrets.GITHUB_TOKEN }}
+          " > ~/.gradle/gradle.properties
+          
+          gradle publishGitHub || echo "Failed to publish to GitHub"
+          gradle publishGitLab || echo "Failed to publish to GitLab"
+      - name: Automatic Releases
+        uses: marvinpinto/action-automatic-releases@latest
+        with:
+          repo_token: "${{ secrets.GITHUB_TOKEN }}"
+          automatic_release_tag: "${{ env.VERSION }}"
+          prerelease: false
+          title: "${{ env.VERSION }}"
+          files: |
+            build/libs/*.jar
+      - name: "README.md Render"
+        uses: varunsridharan/action-dynamic-readme@main
+        with:
+          committer_name: "Radu Voinea"
+          committer_email: "contact@voienaradu.com"
+          commit_message: "Updated README.md versions"
+          files: |
+            template/README-template.md=README.md
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          VERSION: ${{ env.VERSION }}
+          ARTIFACT: ${{ env.ARTIFACT }}
+          GROUP: ${{ env.GROUP }}
+          GITHUB_USERNAME: ${{ github.REPOSITORY_OWNER }}
+          REPOSITORY: ${{ github.REPOSITORY }}
+          REPOSITORY_NAME: ${{ env.REPOSITORY_NAME }}
+
+      - name: "Setup Python3"
+        uses: actions/setup-python@v4
+        with:
+          python-version: '3.10' 
+
+      - name: "Updating remote report"
+        run: |
+          python3 run/dependencies.py
+          git clone https://github.com/L1ghtDream/raport
+          cp run/process.queue raport/process.queue
+          cd raport
+          git add *
+          git checkout -b "${{ env.ARTIFACT }}/${{ env.VERSION }}"
+          git config --global user.email "admin@voinearadu.com"
+          git config --global user.name "Radu Voinea"
+          git commit -m "${{ env.ARTIFACT }}/${{ env.VERSION }}"
+          git remote set-url origin https://L1ghtDream:${{ secrets.PERSONAL_TOKEN }}@github.com/L1ghtDream/raport
+          git push --set-upstream origin ${{ env.ARTIFACT }}/${{ env.VERSION }}
